SYSTO.models.conceptual_modelling1 = 
{
"meta":{
    "language":"wcs_conceptual_modelling"},
"nodes":{
   "goal1":{"type":"goal","id":"goal1","centrex":740,"centrey":234,"text_shiftx":0,"text_shifty":-30,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Conserve wildlife and their habitat in the Putumayo landscape","original_label":"goal1"},
   "target1":{"type":"target","id":"target1","centrex":624,"centrey":126,"text_shiftx":0,"text_shifty":-15,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Giant otter","original_label":"target1"},
   "target2":{"type":"target","id":"target2","centrex":621,"centrey":234,"text_shiftx":0,"text_shifty":-15,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"White-lipped peccary","original_label":"target2"},
   "target3":{"type":"target","id":"target3","centrex":622,"centrey":360,"text_shiftx":0,"text_shifty":-15,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Native landscape","original_label":"target3"},
   "direct_threat1":{"type":"direct_threat","id":"direct_threat1","centrex":500,"centrey":60,"text_shiftx":0,"text_shifty":-20,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Deaths from oil pollution","original_label":"direct_threat1"},
   "direct_threat2":{"type":"direct_threat","id":"direct_threat2","centrex":500,"centrey":140,"text_shiftx":0,"text_shifty":-20,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Unsustainable fishing","original_label":"direct_threat2"},
   "direct_threat3":{"type":"direct_threat","id":"direct_threat3","centrex":499,"centrey":227,"text_shiftx":0,"text_shifty":-20,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Unsustainable hunting","original_label":"direct_threat3"},
   "direct_threat4":{"type":"direct_threat","id":"direct_threat4","centrex":500,"centrey":306,"text_shiftx":0,"text_shifty":-20,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Farming and ranching","original_label":"direct_threat4"},
   "direct_threat5":{"type":"direct_threat","id":"direct_threat5","centrex":499,"centrey":397,"text_shiftx":0,"text_shifty":-20,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Logging","original_label":"direct_threat5"},
   "intervention1":{"type":"intervention","id":"intervention1","centrex":349,"centrey":54,"text_shiftx":0,"text_shifty":-15,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Info to oil watch","original_label":"intervention1"},
   "indirect_threat1":{"type":"indirect_threat","id":"indirect_threat1","centrex":346,"centrey":167,"text_shiftx":0,"text_shifty":-20,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Park borders not enforced","original_label":"indirect_threat1"},
   "indirect_threat2":{"type":"indirect_threat","id":"indirect_threat2","centrex":354,"centrey":295,"text_shiftx":0,"text_shifty":-20,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Anarchic colonization","original_label":"indirect_threat2"},
   "indirect_threat3":{"type":"indirect_threat","id":"indirect_threat3","centrex":219,"centrey":174,"text_shiftx":0,"text_shifty":-20,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Weak management capacity","original_label":"indirect_threat3"},
   "indirect_threat4":{"type":"indirect_threat","id":"indirect_threat4","centrex":220,"centrey":290,"text_shiftx":0,"text_shifty":-20,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Insecure land tenure","original_label":"indirect_threat4"},
   "indirect_threat5":{"type":"indirect_threat","id":"indirect_threat5","centrex":90,"centrey":170,"text_shiftx":0,"text_shifty":-20,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Lack of planning skills","original_label":"indirect_threat5"},
   "indirect_threat6":{"type":"indirect_threat","id":"indirect_threat6","centrex":91,"centrey":253,"text_shiftx":0,"text_shifty":-20,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Lack of planning info","original_label":"indirect_threat6"},
   "intervention2":{"type":"intervention","id":"intervention2","centrex":217,"centrey":82,"text_shiftx":0,"text_shifty":-15,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Government capacity","original_label":"intervention2"},
   "intervention3":{"type":"intervention","id":"intervention3","centrex":221,"centrey":388,"text_shiftx":0,"text_shifty":-15,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Land titling","original_label":"intervention3"},
   "intervention4":{"type":"intervention","id":"intervention4","centrex":89,"centrey":83,"text_shiftx":0,"text_shifty":-15,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"FCUNAE training","original_label":"intervention4"},
   "intervention5":{"type":"intervention","id":"intervention5","centrex":109,"centrey":334,"text_shiftx":0,"text_shifty":-15,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Research on wildlife","original_label":"intervention5"},
   "intervention6":{"type":"intervention","id":"intervention6","centrex":56,"centrey":407,"text_shiftx":0,"text_shifty":-15,"dragging":true,"status":null,"eval_level":null,"set_state":"unset","select_state":"normal","previous_select_state":"normal","label":"Monitor land use","original_label":"intervention6"}
},

"arcs":{
   "link1":{"type":"link","id":"link1","start_node_id":"indirect_threat3","end_node_id":"indirect_threat1","node_id":null,"dragging":false,"label":"link1"},
   "link2":{"type":"link","id":"link2","start_node_id":"indirect_threat4","end_node_id":"indirect_threat2","node_id":null,"dragging":false,"label":"link2"},
   "link3":{"type":"link","id":"link3","start_node_id":"indirect_threat5","end_node_id":"indirect_threat3","node_id":null,"dragging":false,"label":"link3"},
   "link4":{"type":"link","id":"link4","start_node_id":"indirect_threat6","end_node_id":"indirect_threat3","node_id":null,"dragging":false,"label":"link4"},
   "link5":{"type":"link","id":"link5","start_node_id":"target1","end_node_id":"goal1","node_id":null,"dragging":false,"label":"link5"},
   "link6":{"type":"link","id":"link6","start_node_id":"target2","end_node_id":"goal1","node_id":null,"dragging":false,"label":"link6"},
   "link7":{"type":"link","id":"link7","start_node_id":"target3","end_node_id":"goal1","node_id":null,"dragging":false,"label":"link7"},
   "link8":{"type":"link","id":"link8","start_node_id":"direct_threat1","end_node_id":"target1","node_id":null,"dragging":false,"label":"link8"},
   "link9":{"type":"link","id":"link9","start_node_id":"direct_threat2","end_node_id":"target1","node_id":null,"dragging":false,"label":"link9"},
   "link10":{"type":"link","id":"link10","start_node_id":"direct_threat3","end_node_id":"target1","node_id":null,"dragging":false,"label":"link10"},
   "link11":{"type":"link","id":"link11","start_node_id":"direct_threat1","end_node_id":"target2","node_id":null,"dragging":false,"label":"link11"},
   "link12":{"type":"link","id":"link12","start_node_id":"direct_threat2","end_node_id":"target2","node_id":null,"dragging":false,"label":"link12"},
   "link13":{"type":"link","id":"link13","start_node_id":"direct_threat3","end_node_id":"target2","node_id":null,"dragging":false,"label":"link13"},
   "link14":{"type":"link","id":"link14","start_node_id":"intervention1","end_node_id":"direct_threat1","node_id":null,"dragging":false,"label":"link14"},
   "link15":{"type":"link","id":"link15","start_node_id":"indirect_threat1","end_node_id":"direct_threat2","node_id":null,"dragging":false,"label":"link15"},
   "link16":{"type":"link","id":"link16","start_node_id":"indirect_threat1","end_node_id":"direct_threat3","node_id":null,"dragging":false,"label":"link16"},
   "link17":{"type":"link","id":"link17","start_node_id":"indirect_threat1","end_node_id":"direct_threat4","node_id":null,"dragging":false,"label":"link17"},
   "link18":{"type":"link","id":"link18","start_node_id":"indirect_threat1","end_node_id":"direct_threat5","node_id":null,"dragging":false,"label":"link18"},
   "link19":{"type":"link","id":"link19","start_node_id":"indirect_threat2","end_node_id":"direct_threat2","node_id":null,"dragging":false,"label":"link19"},
   "link20":{"type":"link","id":"link20","start_node_id":"indirect_threat2","end_node_id":"direct_threat3","node_id":null,"dragging":false,"label":"link20"},
   "link21":{"type":"link","id":"link21","start_node_id":"indirect_threat2","end_node_id":"direct_threat4","node_id":null,"dragging":false,"label":"link21"},
   "link22":{"type":"link","id":"link22","start_node_id":"indirect_threat2","end_node_id":"direct_threat5","node_id":null,"dragging":false,"label":"link22"},
   "link23":{"type":"link","id":"link23","start_node_id":"intervention3","end_node_id":"indirect_threat4","node_id":null,"dragging":false,"label":"link23"},
   "link24":{"type":"link","id":"link24","start_node_id":"intervention2","end_node_id":"indirect_threat3","node_id":null,"dragging":false,"label":"link24"},
   "link25":{"type":"link","id":"link25","start_node_id":"intervention4","end_node_id":"indirect_threat5","node_id":null,"dragging":false,"label":"link25"},
   "link26":{"type":"link","id":"link26","start_node_id":"intervention5","end_node_id":"indirect_threat6","node_id":null,"dragging":false,"label":"link26"},
   "link27":{"type":"link","id":"link27","start_node_id":"intervention6","end_node_id":"indirect_threat6","node_id":null,"dragging":false,"label":"link27"},
   "link28":{"type":"link","id":"link28","start_node_id":"direct_threat4","end_node_id":"target3","node_id":null,"dragging":false,"label":"link28"},
   "link29":{"type":"link","id":"link29","start_node_id":"direct_threat5","end_node_id":"target3","node_id":null,"dragging":false,"label":"link29"}
}}

