{ "class": "go.GraphLinksModel",
  "linkLabelKeysProperty": "labelKeys",
  "modelData": {"id":"global_carbon", "name":"global_carbon", "title":"no title", "description":"no description", "author":"no author"},
  "nodeDataArray": [ 
{"key":"stock1", "category":"stock", "label":"Atmosphere", "loc":"185 126", "text_shift":"0.5 0.5 44 1", "equation":"562", "has_equation":true, "flag1":true, "fill":"#ffa0ff"},
{"key":"stock2", "category":"stock", "label":"Vegetation", "loc":"185 286", "text_shift":"0.5 0.5 50 26", "equation":"800", "has_equation":true, "flag1":true, "fill":"#ffa0ff"},
{"key":"stock3", "category":"stock", "label":"Soils", "loc":"456 206", "text_shift":"0.5 0.5 37 21", "equation":"1500", "has_equation":true, "flag1":true, "fill":"#ffa0ff"},
{"key":"valve1", "category":"valve", "label":"litterfall", "loc":"320.5 246", "text_shift":"0.5 0.5 34 20", "equation":"veg_tr*Vegetation", "has_equation":true, "fill":"#ffa0ff"},
{"key":"valve2", "category":"valve", "label":"photosynthesis", "loc":"104.535400390625 206", "text_shift":"0.5 0.5 3 39", "equation":"(Atmosphere*max_vp)/(Atmosphere+k_vp)", "has_equation":true, "fill":"#ffa0ff"},
{"key":"valve3", "category":"valve", "label":"combustion", "loc":"196.928466796875 206", "text_shift":"0.5 0.5 44 21", "equation":"0", "has_equation":true, "fill":"#ffa0ff"},
{"key":"valve5", "category":"valve", "label":"soil_resp", "loc":"320.5 166", "text_shift":"0.5 0.5 32 36", "equation":"sc_tr*Soils*temp_resp", "has_equation":true, "fill":"#ffa0ff"},
{"key":"valve6", "category":"valve", "label":"veg_resp", "loc":"277.39306640625 206", "text_shift":"0.5 0.5 31 7", "equation":"ar_frac*photosynthesis+0*Vegetation", "has_equation":true, "fill":"#ffa0ff"},
{"key":"variable2", "category":"variable", "label":"ar_frac", "loc":"280 330", "text_shift":"0.5 0.5 0 20", "equation":"0.45", "has_equation":true},
{"key":"variable3", "category":"variable", "label":"veg_tr", "loc":"343 303", "text_shift":"0.5 0.5 0 20", "equation":"0.07", "has_equation":true},
{"key":"variable4", "category":"variable", "label":"sc_tr", "loc":"447 127", "text_shift":"0.5 0.5 0 20", "equation":"0.04", "has_equation":true},
{"key":"variable5", "category":"variable", "label":"max_vp", "loc":"22 110", "text_shift":"0.5 0.5 0 20", "equation":"182", "has_equation":true},
{"key":"variable6", "category":"variable", "label":"k_vp", "loc":"25 160", "text_shift":"0.5 0.5 0 20", "equation":"500", "has_equation":true},
{"key":"variable7", "category":"variable", "label":"base", "loc":"402 9", "text_shift":"0.5 0.5 0 20", "equation":"2", "has_equation":true},
{"key":"variable8", "category":"variable", "label":"modif", "loc":"434 58", "text_shift":"0.5 0.5 0 20", "equation":"20", "has_equation":true},
{"key":"variable9", "category":"variable", "label":"temp_resp", "loc":"339 85", "text_shift":"0.5 0.5 0 20", "equation":"base*exp(modif*(global_temp-25)/(global_temp+273.2))", "has_equation":true},
{"key":"variable10", "category":"variable", "label":"global_temp", "loc":"254 46", "text_shift":"0.5 0.5 0 20", "equation":"base_temp+Atmosphere*co2_warm", "has_equation":true},
{"key":"variable11", "category":"variable", "label":"base_temp", "loc":"124 22", "text_shift":"0.5 0.5 0 20", "equation":"12.0", "has_equation":true},
{"key":"variable12", "category":"variable", "label":"co2_warm", "loc":"124 57", "text_shift":"0.5 0.5 0 20", "equation":"0.01", "has_equation":true}
 ],
  "linkDataArray": [ 
{"key":"flow1", "category":"flow", "from":"stock2", "to":"stock3", "labelKeys":[ "valve1" ]},
{"key":"flow2", "category":"flow", "from":"stock1", "to":"stock2", "labelKeys":[ "valve2" ]},
{"key":"flow3", "category":"flow", "from":"stock2", "to":"stock1", "labelKeys":[ "valve3" ]},
{"key":"flow5", "category":"flow", "from":"stock3", "to":"stock1", "labelKeys":[ "valve5" ]},
{"key":"flow6", "category":"flow", "from":"stock2", "to":"stock1", "labelKeys":[ "valve6" ]},
{"category":"influence", "from":"stock3", "to":"valve5"},
{"category":"influence", "from":"stock2", "to":"valve1"},
{"category":"influence", "from":"stock1", "to":"valve2"},
{"category":"influence", "from":"variable5", "to":"valve2"},
{"category":"influence", "from":"variable6", "to":"valve2"},
{"category":"influence", "from":"stock2", "to":"valve6"},
{"category":"influence", "from":"variable2", "to":"valve6"},
{"category":"influence", "from":"variable3", "to":"valve1"},
{"category":"influence", "from":"variable10", "to":"variable9"},
{"category":"influence", "from":"variable9", "to":"valve5"},
{"category":"influence", "from":"variable4", "to":"valve5"},
{"category":"influence", "from":"variable7", "to":"variable9"},
{"category":"influence", "from":"variable8", "to":"variable9"},
{"category":"influence", "from":"valve2", "to":"valve6"},
{"category":"influence", "from":"variable11", "to":"variable10"},
{"category":"influence", "from":"variable12", "to":"variable10"},
{"category":"influence", "from":"stock1", "to":"variable10"}
 ]}